_target_: torch_mist.estimate_mi

verbose: true

# Estimation parameters
estimator: smile
hidden_dims:
  - ${h_dim}
neg_samples: 8
tau: 5

# Training parameters
early_stopping: True
patience: 20
max_iterations: 10000
warmup_percentage: 0.01
batch_size: 64
device: ${device.hardware}
num_workers: 0